# ~/.config/zsh_setup/templates/p10k.zsh
# Powerlevel10k 配置模板
# 运行 'p10k configure' 生成完整配置

# 基础配置
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%K{white}%F{black} $POWERLEVEL9K_PROMPT_CHAR %f%k%F{white}%f "

# 左侧提示符元素
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    context
    dir
    vcs
    prompt_char
)

# 右侧提示符元素
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status
    command_execution_time
    background_jobs
    node_version
    go_version
    python_version
    rust_version
    docker_context
    kubecontext
)

# 目录配置
POWERLEVEL9K_DIR_BACKGROUND='4'
POWERLEVEL9K_DIR_FOREGROUND='254'
POWERLEVEL9K_SHORTEN_STRATEGY='truncate_to_unique'
POWERLEVEL9K_SHORTEN_DELIMITER='..'

# Git 配置
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='2'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='0'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='2'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='0'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='3'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='0'

# 状态配置
POWERLEVEL9K_STATUS_OK=false
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='1'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='254'

# 命令执行时间配置
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='3'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='0'

# Node.js 配置
POWERLEVEL9K_NODE_VERSION_BACKGROUND='2'
POWERLEVEL9K_NODE_VERSION_FOREGROUND='0'
POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true

# Go 配置
POWERLEVEL9K_GO_VERSION_BACKGROUND='6'
POWERLEVEL9K_GO_VERSION_FOREGROUND='0'
POWERLEVEL9K_GO_VERSION_PROJECT_ONLY=true

# Python 配置
POWERLEVEL9K_PYTHON_VERSION_BACKGROUND='3'
POWERLEVEL9K_PYTHON_VERSION_FOREGROUND='0'
POWERLEVEL9K_PYTHON_VERSION_PROJECT_ONLY=true

# Rust 配置
POWERLEVEL9K_RUST_VERSION_BACKGROUND='208'
POWERLEVEL9K_RUST_VERSION_FOREGROUND='0'
POWERLEVEL9K_RUST_VERSION_PROJECT_ONLY=true

# Docker 配置
POWERLEVEL9K_DOCKER_CONTEXT_BACKGROUND='6'
POWERLEVEL9K_DOCKER_CONTEXT_FOREGROUND='0'

# Kubernetes 配置
POWERLEVEL9K_KUBECONTEXT_BACKGROUND='6'
POWERLEVEL9K_KUBECONTEXT_FOREGROUND='0'
